"""empty message

Revision ID: 40324faaecdd
Revises: 
Create Date: 2025-06-11 16:19:29.308086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40324faaecdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_checked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('is_checked')

    # ### end Alembic commands ###
