"""empty message

Revision ID: 428897fff00b
Revises: ae9101ff7168
Create Date: 2025-06-17 02:15:40.085427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428897fff00b'
down_revision = 'ae9101ff7168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favourites_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['user_id'], ['user_id'])

    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('inscriptions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['user_id'], ['user_id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reports_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['user_id'], ['user_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reviews_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reviews_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reports_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('inscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('inscriptions_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favourites_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
