"""empty message

Revision ID: 7687fb94139a
Revises: b6e6129ae474
Create Date: 2025-06-02 18:18:47.146831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7687fb94139a'
down_revision = 'b6e6129ae474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('profesional_rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('activity_rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('profesional_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('activity_message',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('activity_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('profesional_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('activity_rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('profesional_rating',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
