"""empty message

Revision ID: 7a8c7a6d56fe
Revises: 5f06343c279d
Create Date: 2025-06-11 21:08:47.843244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a8c7a6d56fe'
down_revision = '5f06343c279d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', postgresql.ENUM('user', 'activity', name='enumreps'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
