"""empty message

Revision ID: 8f345d4c4e5d
Revises: d9d47401568c
Create Date: 2025-06-02 17:25:36.476810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f345d4c4e5d'
down_revision = 'd9d47401568c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_profesional_id_profesionals', type_='foreignkey')  # Añade el nombre real de la FK aquí
        batch_op.drop_column('profesional_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('tax_address')

    with op.batch_alter_table('info_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profesional_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False))
        batch_op.create_foreign_key('fk_info_activities_profesional_id', 'profesionals', ['profesional_id'], ['user_id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('profesional_target_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('activity_target_id',
               existing_type=sa.INTEGER(),
               nullable=True)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('activity_target_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('profesional_target_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('info_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rating')
        batch_op.drop_column('location')
        batch_op.drop_column('profesional_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_address', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profesional_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'profesionals', ['profesional_id'], ['user_id'])

    # ### end Alembic commands ###
