"""empty message

Revision ID: ff55866c96d1
Revises: 
Create Date: 2025-06-24 23:07:10.349355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff55866c96d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('administrators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('clients',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=40), nullable=False),
    sa.Column('telephone', sa.String(length=15), nullable=False),
    sa.Column('NID', sa.String(length=10), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'not_telling', name='enumclts'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('NID'),
    sa.UniqueConstraint('telephone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('professionals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('freelance', 'business', name='enumprof'), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('tax_address', sa.String(), nullable=False),
    sa.Column('nuss', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('info_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('tourism', 'leisure', 'sport', name='enuminfo'), nullable=False),
    sa.Column('location', sa.String(length=60), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('meeting_point', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['info_id'], ['info_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('info_activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['info_activity_id'], ['info_activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['clients.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'info_activity_id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_activity_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['info_activity_id'], ['info_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('professional_target_id', sa.Integer(), nullable=True),
    sa.Column('activity_target_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_target_id'], ['info_activities.id'], name='fk_reports_activity_target_id'),
    sa.ForeignKeyConstraint(['professional_target_id'], ['professionals.user_id'], name='fk_reports_professional_target_id'),
    sa.ForeignKeyConstraint(['user_id'], ['clients.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_activity_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('professional_rating', sa.Float(), nullable=True),
    sa.Column('activity_rating', sa.Float(), nullable=True),
    sa.Column('professional_message', sa.String(), nullable=True),
    sa.Column('activity_message', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['info_activity_id'], ['info_activities.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['clients.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inscription_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payment_intent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['clients.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscriptions')
    op.drop_table('reviews')
    op.drop_table('reports')
    op.drop_table('media')
    op.drop_table('favourites')
    op.drop_table('activities')
    op.drop_table('info_activities')
    op.drop_table('professionals')
    op.drop_table('clients')
    op.drop_table('administrators')
    op.drop_table('users')
    # ### end Alembic commands ###
